name: build

on:
  pull_request:
    branches:
      - main
    paths:
      - '**/*.swift'
      - '.github/workflows/build.yml'

jobs:
  build:
    runs-on: windows-latest

    strategy:
      matrix:
        include:
          - branch: swift-5.8.1-release
            tag: 5.8.1-RELEASE

    name: Swift ${{ matrix.tag }}
    steps:
      - uses: compnerd/gha-setup-swift@main
        with:
          tag: ${{ matrix.tag }}
          branch: ${{ matrix.branch }}
      - uses: actions/checkout@v2
      - run: swift build
      - run: swift test
